sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
    sonarcloud:
       organization: "metamagic" # the key of the org you chose at step #3
       token:
         secure: c5f99f1430c7c379e0e4dec089a81b244d57c598 # encrypted value of your token  

language: node_js
node_js:
  - "8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --global gulp --save
  - gem install sass

            
script: 
  - cd src/styles/ && sh sasstocss.sh
  - cd ../../ && pwd && gulp build
  - cd dist && npm pack
  
after_success: gulp coveralls

cache:
  yarn: true
  
