sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --global gulp --save
  - npm install node-sass
  - sudo apt-get -y update
  - sudo apt-get -y install ruby-full
  - sudo apt install ruby-sass
  - gem install bundler
            

  
script: 
  - sh src/styles/sasstocss.sh
  - gulp build
  - cd dist && npm pack
after_success: gulp coveralls

cache:
  yarn: true
  
