sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "metamagic" # the key of the org you chose at step #3
    token:
      secure: 7228cab59b6ad1555c79b912123d47e2edc47d4e # encrypted value of your token   
 
language: node_js
node_js:
  - "8"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --global gulp --save
  - gem install sass
  - git fetch --unshallow

            
script: 
  - gulp test
  - sonar-scanner
  - cd src/styles/ && sh sasstocss.sh
  - cd ../../ && pwd && gulp build
  - cd dist && npm pack
  
after_success: 
  - gulp coveralls
  - codecov

cache:
  yarn: true
  
